// src/styles/theme.js

export const theme = {
  colors: {
    bg: '#f6f6f7',
    cardBg: '#ffffff',
    textPrimary: '#202223',
    textSecondary: '#637381',
    border: '#e1e3e5',
    borderInput: '#babfc3',
    primary: '#008060',
    primaryHover: '#006e52',
    primaryDisabled: '#b5b5b5',
    successBg: '#e4f5e4',
    successText: '#008060',
    successBorder: '#aee9ae',
    errorBg: '#fef2f0',
    errorText: '#d72c0d',
    errorBorder: '#fecdc4',
    warningBg: '#fef3cd',
    warningText: '#8a6d3b',
    infoBg: '#f0f7ff',
    infoBorder: '#c3ddf8',
    infoText: '#005bd3',
    badgeSuccessBg: '#e3f9e5',
    badgeInfoBg: '#eaf2ff',
  },
  shadows: {
    card: '0 1px 3px rgba(0, 0, 0, 0.04), 0 4px 12px rgba(0, 0, 0, 0.04)',
  },
  radius: {
    sm: '6px',
    md: '8px',
    lg: '12px',
  },
}

export const styles = {
  page: {
    padding: '40px 20px 80px',
    fontFamily:
      'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    background: theme.colors.bg,
    minHeight: '100vh',
    display: 'flex',
    justifyContent: 'center',
  },
  container: {
    maxWidth: '680px',
    width: '100%',
  },
  centerBox: {
    padding: '80px 20px',
    textAlign: 'center',
    fontFamily: 'Inter, sans-serif',
  },
  h1: {
    fontSize: '26px',
    fontWeight: '700',
    color: theme.colors.textPrimary,
    marginBottom: '6px',
    letterSpacing: '-0.5px',
    margin: '0 0 6px 0',
  },
  h2: {
    fontSize: '17px',
    fontWeight: '700',
    marginBottom: '22px',
    color: theme.colors.textPrimary,
    margin: '0 0 22px 0',
    display: 'flex',
    alignItems: 'center',
  },
  subtitle: {
    color: theme.colors.textSecondary,
    fontSize: '14.5px',
    marginBottom: '22px',
    margin: '0 0 22px 0',
    lineHeight: '1.5',
  },
  card: {
    background: theme.colors.cardBg,
    border: `1px solid ${theme.colors.border}`,
    borderRadius: theme.radius.lg,
    padding: '28px 32px',
    marginBottom: '20px',
    boxShadow: theme.shadows.card,
  },
  label: {
    display: 'block',
    fontSize: '13.5px',
    fontWeight: '600',
    marginBottom: '8px',
    color: theme.colors.textPrimary,
  },
  input: {
    width: '100%',
    padding: '11px 14px',
    border: `1px solid ${theme.colors.borderInput}`,
    borderRadius: theme.radius.md,
    fontSize: '14.5px',
    outline: 'none',
    boxSizing: 'border-box',
    marginBottom: '18px',
    color: theme.colors.textPrimary,
    transition: 'border-color 0.2s, box-shadow 0.2s',
    fontFamily: 'inherit',
  },
  primaryBtn: {
    width: '100%',
    color: 'white',
    border: 'none',
    padding: '14px 24px',
    borderRadius: theme.radius.md,
    fontSize: '15px',
    fontWeight: '600',
    transition: 'all 0.2s',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '8px',
    letterSpacing: '0.2px',
  },
  helpText: {
    marginTop: '8px',
    fontSize: '12.5px',
    color: theme.colors.textSecondary,
    margin: '8px 0 0 0',
    lineHeight: '1.5',
  },
  badgeRow: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    marginBottom: '22px',
  },
  infoBox: {
    background: '#ffffff',
    borderRadius: theme.radius.lg,
    padding: '22px 24px',
    fontSize: '13.5px',
    color: theme.colors.textSecondary,
    lineHeight: '1.7',
    marginBottom: '16px',
    border: `1px solid ${theme.colors.border}`,
    boxShadow: theme.shadows.card,
  },
  securityBox: {
    padding: '14px 18px',
    background: theme.colors.infoBg,
    border: `1px solid ${theme.colors.infoBorder}`,
    borderRadius: theme.radius.md,
    fontSize: '12.5px',
    color: theme.colors.infoText,
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    lineHeight: '1.5',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
    gap: '20px',
  },
  planCard: {
    background: 'white',
    border: `2px solid ${theme.colors.border}`,
    borderRadius: theme.radius.lg,
    padding: '24px',
  },
}